class { '::samba::server' : 
  workgroup            => '{{WORKGROUP}}',
  server_string        => '{{SERVER_STRING}}',
  netbios_name         => '{{NETBIOS_NAME}}',
  interfaces           => [ 'lo', 'eth0' ],
  hosts_allow          => [ '127.', '192.168.' ],
  local_master         => 'yes',
  map_to_guest         => 'Bad User',
  os_level             => '50',
  preferred_master     => 'yes',
  ldap_suffix          => 'dc={{LDAP_SUFFIX}}',
  ldap_url             => 'ldap://localhost',
  ldap_ssl             => '{{LDAP_SSL}}',
  ldap_admin_dn        => '{{LDAP_ADMIN_DN}}',
  ldap_group_suffix    => 'ou={{LDAP_GROUP_SUFFIX}}',
  ldap_machine_suffix  => 'ou={{LDAP_MACHINE_SUFFIX}}',
  ldap_user_suffix     => 'ou={{LDAP_USER_SUFFIX}}',
  shares => {
    'homes' => [
      'comment = Home Directories',
      'browseable = no',
      'writable = yes',
    ],
  },
  selinux_enable_home_dirs => true,
}